INSERT INTO java_zoekterm (zoekterm,categorie,packagenaam,opmerking,import_controle) VALUES
	 ('synchronized','keywords','','(code block) or (methods)',false),
	 ('volatile','keywords','',NULL,false),
	 ('Runnable','interfaces','java.lang',NULL,false),
	 ('BlockingDeque','interfaces','java.util.concurrent',NULL,true),
	 ('BlockingQueue','interfaces','java.util.concurrent',NULL,true),
	 ('Callable','interfaces','java.util.concurrent',NULL,true),
	 ('CompletableFuture.AsynchronousCompletionTask','interfaces','java.util.concurrent',NULL,true),
	 ('CompletionService','interfaces','java.util.concurrent',NULL,true),
	 ('CompletionStage','interfaces','java.util.concurrent',NULL,true),
	 ('ConcurrentMap','interfaces','java.util.concurrent',NULL,true);
INSERT INTO java_zoekterm (zoekterm,categorie,packagenaam,opmerking,import_controle) VALUES
	 ('ConcurrentNavigableMap','interfaces','java.util.concurrent',NULL,true),
	 ('Delayed','interfaces','java.util.concurrent',NULL,true),
	 ('Executor','interfaces','java.util.concurrent',NULL,true),
	 ('ExecutorService','interfaces','java.util.concurrent',NULL,true),
	 ('Flow.Processor','interfaces','java.util.concurrent',NULL,true),
	 ('Flow.Publisher','interfaces','java.util.concurrent',NULL,true),
	 ('Flow.Subscriber','interfaces','java.util.concurrent',NULL,true),
	 ('Flow.Subscription','interfaces','java.util.concurrent',NULL,true),	 
	 ('ForkJoinPool.ForkJoinWorkerThreadFactory','interfaces','java.util.concurrent',NULL,true),
	 ('ForkJoinPool.ManagedBlocker','interfaces','java.util.concurrent',NULL,true),
	 ('Future','interfaces','java.util.concurrent',NULL,true),
	 ('RejectedExecutionHandler','interfaces','java.util.concurrent',NULL,true),
	 ('RunnableFuture','interfaces','java.util.concurrent',NULL,true),
	 ('RunnableScheduledFuture','interfaces','java.util.concurrent',NULL,true);
INSERT INTO java_zoekterm (zoekterm,categorie,packagenaam,opmerking,import_controle) VALUES
	 ('ScheduledExecutorService','interfaces','java.util.concurrent',NULL,true),
	 ('ThreadFactory','interfaces','java.util.concurrent',NULL,true),
	 ('TransferQueue','interfaces','java.util.concurrent',NULL,true),
	 ('Condition','interfaces','java.util.concurrent.locks',NULL,true),
	 ('Lock','interfaces','java.util.concurrent.locks',NULL,true),
	 ('ReadWriteLock','interfaces','java.util.concurrent.locks',NULL,true),
	 ('Thread','classes','java.lang',NULL,false),
	 ('ThreadGroup','classes','java.lang',NULL,false),
	 ('ThreadLocal','classes','java.lang',NULL,false),
	 ('InheritableThreadLocal','classes','java.lang',NULL,false),
	 ('AbstractExecutorService','classes','java.util.concurrent',NULL,true),
	 ('ArrayBlockingQueue','classes','java.util.concurrent',NULL,true),
	 ('CompletableFuture','classes','java.util.concurrent',NULL,true),
	 ('ConcurrentHashMap','classes','java.util.concurrent',NULL,true);
INSERT INTO java_zoekterm (zoekterm,categorie,packagenaam,opmerking,import_controle) VALUES
	 ('ConcurrentHashMap.KeySetView','classes','java.util.concurrent',NULL,true),
	 ('ConcurrentLinkedDeque','classes','java.util.concurrent',NULL,true),
	 ('ConcurrentLinkedQueue','classes','java.util.concurrent',NULL,true),
	 ('ConcurrentSkipListMap','classes','java.util.concurrent',NULL,true),
	 ('ConcurrentSkipListSet','classes','java.util.concurrent',NULL,true),
	 ('CopyOnWriteArrayList','classes','java.util.concurrent',NULL,true),
	 ('CopyOnWriteArraySet','classes','java.util.concurrent',NULL,true),
	 ('CountDownLatch','classes','java.util.concurrent',NULL,true),
	 ('CountedCompleter','classes','java.util.concurrent',NULL,true),
	 ('CyclicBarrier','classes','java.util.concurrent',NULL,true);
INSERT INTO java_zoekterm (zoekterm,categorie,packagenaam,opmerking,import_controle) VALUES
	 ('DelayQueue','classes','java.util.concurrent',NULL,true),
	 ('Exchanger','classes','java.util.concurrent',NULL,true),
	 ('ExecutorCompletionService','classes','java.util.concurrent',NULL,true),
	 ('Executors','classes','java.util.concurrent',NULL,true),
	 ('Flow','classes','java.util.concurrent',NULL,true),
	 ('ForkJoinPool','classes','java.util.concurrent',NULL,true),
	 ('ForkJoinTask','classes','java.util.concurrent',NULL,true),
	 ('ForkJoinWorkerThread','classes','java.util.concurrent',NULL,true),
	 ('FutureTask','classes','java.util.concurrent',NULL,true),
	 ('LinkedBlockingDeque','classes','java.util.concurrent',NULL,true),
	 ('LinkedBlockingQueue','classes','java.util.concurrent',NULL,true);
INSERT INTO java_zoekterm (zoekterm,categorie,packagenaam,opmerking,import_controle) VALUES
	 ('LinkedTransferQueue','classes','java.util.concurrent',NULL,true),
	 ('Phaser','classes','java.util.concurrent',NULL,true),
	 ('PriorityBlockingQueue','classes','java.util.concurrent',NULL,true),
	 ('RecursiveAction','classes','java.util.concurrent',NULL,true),
	 ('RecursiveTask','classes','java.util.concurrent',NULL,true),
	 ('ScheduledThreadPoolExecutor','classes','java.util.concurrent',NULL,true),
	 ('Semaphore','classes','java.util.concurrent',NULL,true),
	 ('SubmissionPublisher','classes','java.util.concurrent',NULL,true),
	 ('SynchronousQueue','classes','java.util.concurrent',NULL,true),
	 ('ThreadLocalRandom','classes','java.util.concurrent',NULL,true),
	 ('ThreadPoolExecutor','classes','java.util.concurrent',NULL,true);
INSERT INTO java_zoekterm (zoekterm,categorie,packagenaam,opmerking,import_controle) VALUES
	 ('ThreadPoolExecutor.AbortPolicy','classes','java.util.concurrent',NULL,true),
	 ('ThreadPoolExecutor.CallerRunsPolicy','classes','java.util.concurrent',NULL,true),
	 ('ThreadPoolExecutor.DiscardOldestPolicy','classes','java.util.concurrent',NULL,true),
	 ('ThreadPoolExecutor.DiscardPolicy','classes','java.util.concurrent',NULL,true),
	 ('VarHandle','classes','java.lang.invoke',NULL,true),
	 ('AtomicBoolean','classes','java.util.concurrent.atomic',NULL,true),
	 ('AtomicInteger','classes','java.util.concurrent.atomic',NULL,true),
	 ('AtomicLong','classes','java.util.concurrent.atomic',NULL,true),
	 ('AtomicIntegerArray','classes','java.util.concurrent.atomic',NULL,true),
	 ('AtomicIntegerFieldUpdater','classes','java.util.concurrent.atomic',NULL,true),
	 ('AtomicLongArray','classes','java.util.concurrent.atomic',NULL,true),
	 ('AtomicLongFieldUpdater','classes','java.util.concurrent.atomic',NULL,true),
	 ('AtomicMarkableReference','classes','java.util.concurrent.atomic',NULL,true),
	 ('AtomicReference','classes','java.util.concurrent.atomic',NULL,true),
	 ('AtomicReferenceArray','classes','java.util.concurrent.atomic',NULL,true),
	 ('AtomicReferenceFieldUpdater','classes','java.util.concurrent.atomic',NULL,true),
	 ('AtomicStampedReference','classes','java.util.concurrent.atomic',NULL,true),
	 ('DoubleAccumulator','classes','java.util.concurrent.atomic',NULL,true),
	 ('DoubleAdder','classes','java.util.concurrent.atomic',NULL,true),
	 ('LongAccumulator','classes','java.util.concurrent.atomic',NULL,true),
	 ('LongAdder','classes','java.util.concurrent.atomic',NULL,true),
	 ('AbstractOwnableSynchronizer','classes','java.util.concurrent.locks',NULL,true),
	 ('AbstractQueuedLongSynchronizer','classes','java.util.concurrent.locks',NULL,true);
INSERT INTO java_zoekterm (zoekterm,categorie,packagenaam,opmerking,import_controle) VALUES
	 ('AbstractQueuedSynchronizer','classes','java.util.concurrent.locks',NULL,true),
	 ('LockSupport','classes','java.util.concurrent.locks',NULL,true),
	 ('ReentrantLock','classes','java.util.concurrent.locks',NULL,true),
	 ('ReentrantReadWriteLock','classes','java.util.concurrent.locks',NULL,true),
	 ('ReentrantReadWriteLock.ReadLock','classes','java.util.concurrent.locks',NULL,true),
	 ('ReentrantReadWriteLock.WriteLock','classes','java.util.concurrent.locks',NULL,true),
	 ('StampedLock','classes','java.util.concurrent.locks',NULL,true),
	 ('Collections.synchronizedCollection','classes','java.util.collections ',NULL,true),
	 ('Collections.synchronizedList','classes','java.util.collections ',NULL,true),
	 ('Collections.synchronizedMap','classes','java.util.collections ',NULL,true),
	 ('Collections.synchronizedSet','classes','java.util.collections ',NULL,true);
INSERT INTO java_zoekterm (zoekterm,categorie,packagenaam,opmerking,import_controle) VALUES
	 ('Collections.synchronizedSortedMap','classes','java.util.collections ',NULL,true),
	 ('Collections.synchronizedSortedSet','classes','java.util.collections ',NULL,true),
	 ('io.reactivex.rxjava2','libraries',NULL,'RxJava',true),
	 ('org.awaitility','libraries',NULL,'Awaitility',true),
	 ('io.projectreacto','libraries',NULL,'ProjectReactor',true),
	 ('com.lmax','libraries',NULL,'Disruptor',true),
	 ('@Lock','libraries','javax.ejb','J2EE',true),
	 ('@ConcurrencyManagement','libraries','javax.ejb','J2EE',true),
	 ('SwingWorker','classes' ,'javax.swing',NULL,true),
	 ('AsyncBoxView.ChildState','classes','javax.swing.text',NULL,true),
	 ('RenderableImageProducer','classes','java.awt.image.renderable',NULL,true),
	 ('TimerTask','classes','java.util',NULL,true);

-- vul zoekterm vanuit java zoektermen lijst	
insert into zoekterm ( extensie, zoekwoord)
select '.java', j.zoekterm  from java_zoekterm j;

select count(*) from zoekterm;